apiVersion: v1
kind: Pod
metadata:
  name: force-pull-cp4i
  namespace: cp4i
spec:
  containers:
  - name: force-pull-cp4i-base
    imagePullPolicy: Always
    image: DOCKER_REGISTRY/tea-tekton-cp4i:latest
    command: ["sleep"]
    args: ["1"]
  - name: force-pull-cp4i-ct
    imagePullPolicy: Always
    image: DOCKER_REGISTRY/tea-tekton-cp4i-ct:latest  
    command: ["sleep"]
    args: ["1"]
  - name: force-pull-minimal
    imagePullPolicy: Always
    image: DOCKER_REGISTRY/ace-minimal:12.0.8.0-alpine
    command: ["sleep"]
    args: ["1"]
  - name: force-pull-minimal-build
    imagePullPolicy: Always
    image: DOCKER_REGISTRY/ace-minimal-build:12.0.8.0-alpine
    command: ["sleep"]
    args: ["1"]
  restartPolicy: Never
  imagePullSecrets:
  - name: 'regcred'
