name: Push to GitOps repo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gitops-push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Push PR to gitops repo
        shell: bash
        run: |
          set -e
          set -x
          
          git clone https://$GITOPS_GH_USER:$GITOPS_GH_TOKEN@github.com/trevor-dolby-at-ibm-com/ace-demo-gitops.git
          cd ace-demo-gitops
          git checkout autoPr/tea-demo-app 2>/dev/null || git checkout -b autoPr/tea-demo-app # Create branch if it does not exist
          
